-- MySQL Script generated by MySQL Workbench
-- Mon Aug  1 23:50:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cnet_company
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cnet_company
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cnet_company` DEFAULT CHARACTER SET utf8 ;
USE `cnet_company` ;

-- -----------------------------------------------------
-- Table `cnet_company`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cnet_company`.`employees` ;

CREATE TABLE IF NOT EXISTS `cnet_company`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `salary` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO employees VALUES (1, 'Aleksey', 'Turkov', '+375291234567', 'alextur@cnet.com', 800.00);
INSERT INTO employees VALUES (2, 'Ivan', 'Usovich', '+375295896587', 'ivanu@cnet.com', 999.00);
INSERT INTO employees VALUES (3, 'Oleg', 'Starostin', '+375125896875', 'olegst@cnet.com', 640.00);
INSERT INTO employees VALUES (4, 'Maksim', 'Sokolov', '+375293658958', 'maskims@cnet.com', 302.00);
INSERT INTO employees VALUES (5, 'Bogdan', 'Timofeev', '+375291598758', 'bogdant@cnet.com', 1250.00);
INSERT INTO employees VALUES (6, 'Timur', 'Popov', '+375291112233', 'timurp@cnet.com', 2569.00);
INSERT INTO employees VALUES (7, 'Elena', 'Kashtanova', '+375293698521', 'elenak@cnet.com', 111.00);
INSERT INTO employees VALUES (8, 'Olga', 'Ivanova', '+375292859741', 'olgai@cnet.com', 789.00);
INSERT INTO employees VALUES (9, 'Irina', 'Simonova', '+3752598745897', 'irinas@cnet.com', 1020.00);
INSERT INTO employees VALUES (10, 'Aleksey', 'Menchuk', '+375291023699', 'alekseym@cnet.com', 555.00);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
